<?php
$tableParams = array(
	'tableId' 			=> 'online-editor-tree',
    'tableWidth'        => '4',
);
?>

<div style="display: none;">
<select id="online-ide-theme" size="1" class="online-ide-theme">
	<optgroup label="Bright">
		<option value="ace/theme/chrome">Chrome</option>
		<option value="ace/theme/clouds">Clouds</option>
		<option value="ace/theme/crimson_editor">Crimson Editor</option>
		<option value="ace/theme/dawn">Dawn</option>
		<option value="ace/theme/dreamweaver">Dreamweaver</option>
		<option value="ace/theme/eclipse">Eclipse</option>
		<option value="ace/theme/github">GitHub</option>
		<option value="ace/theme/solarized_light">Solarized Light</option>
		<option value="ace/theme/textmate">TextMate</option>
		<option value="ace/theme/tomorrow">Tomorrow</option>
		<option value="ace/theme/xcode">XCode</option>
		<option value="ace/theme/kuroir">Kuroir</option>
		<option value="ace/theme/katzenmilch">KatzenMilch</option>
	</optgroup>
	<optgroup label="Dark">
		<option value="ace/theme/ambiance">Ambiance</option>
		<option value="ace/theme/chaos">Chaos</option>
		<option value="ace/theme/clouds_midnight">Clouds Midnight</option>
		<option value="ace/theme/cobalt">Cobalt</option>
		<option value="ace/theme/idle_fingers">idle Fingers</option>
		<option value="ace/theme/kr_theme">krTheme</option>
		<option value="ace/theme/merbivore">Merbivore</option>
		<option value="ace/theme/merbivore_soft">Merbivore Soft</option>
		<option value="ace/theme/mono_industrial">Mono Industrial</option>
		<option value="ace/theme/monokai">Monokai</option>
		<option value="ace/theme/pastel_on_dark">Pastel on dark</option>
		<option value="ace/theme/solarized_dark">Solarized Dark</option>
		<option value="ace/theme/terminal">Terminal</option>
		<option value="ace/theme/tomorrow_night">Tomorrow Night</option>
		<option value="ace/theme/tomorrow_night_blue">Tomorrow Night Blue</option>
		<option value="ace/theme/tomorrow_night_bright">Tomorrow Night Bright</option>
		<option value="ace/theme/tomorrow_night_eighties">Tomorrow Night 80s</option>
		<option value="ace/theme/twilight">Twilight</option>
		<option value="ace/theme/vibrant_ink">Vibrant Ink</option>
	</optgroup>
</select>
</div>

<div>
    <ul class="tabs">
        <li style="width: 100%;">
            <form id="online-editor-form" style="margin-left: 10px;">
                <label style="display: none;"></label>
            	<input type="text" id="filepath" name="filepath" placeholder="file path" value="" style="width: 60%;">
            	<input type="submit" value="Load"/>
            </form>
        </li>
    </ul>
    <div id="online-editor-runner"></div>
    
    <?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>
</div>

<style>
.online-editor {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background: #fff;
	z-index: 10000;
}

.online-ide-save-btn {
	background:
		url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAACH0lEQVQ4T6WUP2hTURTGv3NfGpNKQekmqIWsOgguioPFwUEFB4VCm6RJBgcrVAfb6FCnmAji4lRMmqZtEAUFnaSSVrqKqw6BInUQHSpoa9LnO58k/kvyXmM0d7pwz/3d852P+0k8k93jEMcUxqDTRThWAIv5y7FPrVdkOH1v1YIZ+H1APBHBSju2IzwrRL9lzGD+aux9Y61E0jm2XA4XJuPzXsBoJhdzKKOGugSRKYJvWqH/BAxnsuOiMg4wXwPWHm2Fdg38oYSlwmTiRG3nAhKYIrXoJZnQ3WJ6dhlyCEC8Ye5vC8l43QevDjv1+k8d0T2QomtCs6jAkCE+dtth2QKitiIifjzWLdxeuBY/8L+Sy7AYgS33YbAPxAtVXJm/Hn/lAlIwLYKnbYdI/QDHPKzDfi4Cy8GKfWr6xoXNJlNIxuaSifx2wNGbMwMKLkOwv7WGwFKwYp92ASvVvmIwsDEmYNPfdnbYJVPpeeQFa4A/dwFD1bVCObD3oM8YaezCVPWr45ejSoQFGHSFAiSrxDN3h6G+ud7VzeNUbQLC0LFsKatPJghe9BhLPQM8JfcGP58npRkIwFDeUXCuLXAkndswyhUYOfnLlEhqtt/2V9zALzu3fAE71RYYTudegrwrIjME7lgiD7Zz+Rt03aK51F5yKnuEImfEoJPEfg3FYQjGXKYIR2YnEgsuWX9LhuitfIjUQ00praSNQKmYHF7/Dp2hK8RZJOIvAAAAAElFTkSuQmCC');
	background-repeat: no-repeat;
	height: 24px;
	width: 24px;
	display: inline-block;
	margin-right: 10px;
}

.online-ide-lock {
	background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAB1UlEQVQ4T63UPU8UURQG4PecmbubWECynwUR1BgKC+1sDEFN/A2UQkjobIwNYXZYBmwI8gNswE4Kai2MNhbGxM7EAk3YQACZkWj8IjOTc8i6avZjWAayU84975N77j0zhB4/lMbLVbUPEfoPfOzhMUXdMl3B/Gx4nZWWAIzUERH5AbZW6NCaCRbpexJ8LJivRretWJ4pcwbQLYC2ReQaM58D8I5/2aOfl+hnO5oMTqkplaKPyjSowIPAs5cB0oFpzYcmXgcwSsD8vmfcVGDBjW4R8FJVXwTzmTvNodyMnrco3FS2aoFnX0oFFt34LqCrICz4c6bSHio60RZYBnwvy+nASjgOohUC5vY9U20PFdxwk0BDvmc6jqzjxeV7mv2Wix0oHIg+UZtW20EVfcqgsohc+bKQ/dC83gLWsa/98VtiXE0zn/WaxqWZR//qW8BSJbqhhNdpsb91G75nhhPBQjW6SYJXiQMrcqDMuY72obXAy1w4Lej4e/ZisRy/B+H/bhotnwFUleequM/AGzD3Ne/yTOAfQHWiPkq9ahkQXQPTWO/AY66+a8tl5/dFYf4EcKr/ZOMkWr/3jmDRjccAmQQoc9I8kuiOpWZ69yHVEsfmJCDN+hHhHdAVHM9yzgAAAABJRU5ErkJggg==');
	background-repeat: no-repeat;
	height: 24px;
	width: 24px;
	float: left;
}

.zdb-table .online-ide-lock {
  background-position: 0 2px;
}

.theme-selector {
	float: left;
    margin-right: 10px;
}

.ace_editor, .ace_editor p, .ace_editor div {
	font-family: 'Monaco', 'Menlo', 'Droid Sans Mono', 'Courier New',
		monospace !important;
	border: auto !important;
}

.online-ide-folder,
.online-ide-file {
    background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAABGUlEQVQ4T+3Uv0rDUBQG8PPdhL6B4J/JB9DBYqKITaK4KDeDs9DBXXDyOdwt+AYiAasOWghIO+hidxen2jdomk8SsEZEyK0Ze+bv/O7lXO6BVFzIvM1Aeyk5N7EBAvLWfYheTM/Dhq/PUqZrCngtNlOwI5Dz3mN0bYLC9fVNbZw047j9UWx0vTAQ8IQirTIgRIa9TtSF2whvE8Wj5040LDY6Db0sSo7LYFmG5IoC4j/BstBXrr59uGBbo1YOQnGJlLEp8jOf2kLrvbIbrvv78yq1L2fg9M8ym+Hvr2c6zckMHV+37ZrdfLq/GpgixfzWXriYjHgBx9OnoOxSSf8/IERWRXCXL1g3OKgrWt8LdgqZioNsIedglfUJV/KsQ21YyLMAAAAASUVORK5CYII=');
	background-repeat: no-repeat;
	cursor: pointer;
	height: 20px;
}
.online-ide-file {
    background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAABIklEQVQ4T2NkgAJTBy8Jpn+Ma2B8dJqRmXHdif1b+nDJw8QZYQwLhwAFBoY/kzkYOCPRNf1g+DHl/38GAwZGhhUnD2zuwGcoioH///2ecPLQ1gB0DRYO3nP+MzDNYWRkKPr/n+EcPkOJNvAfA/MMLoZPF34w8i7DZyhJBp46sOmMg4MDy7f/3EsZGZnOY3MpyQaCggNk6HcG3iUMDAwX0A0l2sD/jEznGP8z3YKF7z/GP8yM/5kmMDAwLEQ2lEgDfcL/MjBYYotdJob/fn/+slufPbzuOUieKAPxJRNzO98tDEx/Mk4e2P5k1MAABVw5ZTQMUUJgiCebf///Tv3FyBxNqFRGlmf/928FA9PvFIycQqgKwGcJ2/9/gYcPb38NUgMAvJAVJEnL+f4AAAAASUVORK5CYII=');
	background-repeat: no-repeat;
}
#zend-dev-bar div.online-ide-folder,
#zend-dev-bar div.online-ide-file {
	padding-left: 27px;
}

#zend-dev-bar div.online-editor-actions-disabled {
    margin: 20px 10px;
    color: #F00;
    font-weight: bold;
    font-size: 16px;
}
</style>

<script type="text/javascript">

(function() {
	if (! zray.actionsEnabled()) {
		jQuery("#online-editor-form :input").prop("disabled", true);
		jQuery('#online-editor-tree').append('<div class="online-editor-actions-disabled">Run actions is disabled. Click here to <a href="' + zendDevBar.baseUrl + '/Z-Ray/AccessMode" target="_blank">enable it.</a></div>');
		return;
	}
	
	var cookieParams = {};
	var editors = [];

	if (typeof jQuery.cookie('ZSDEVBAR_ONLINE_IDE') == 'undefined') {
		jQuery.cookie('ZSDEVBAR_ONLINE_IDE', JSON.stringify({}), {path: '/'});
	} else {
		cookieParams = JSON.parse(jQuery.cookie('ZSDEVBAR_ONLINE_IDE'));
	}
	if (typeof cookieParams.theme != 'undefined') {
		jQuery('#online-ide-theme').val(cookieParams.theme);
	}
	
	function updateCookieParams() {		
		jQuery.cookie('ZSDEVBAR_ONLINE_IDE', JSON.stringify(cookieParams));
	};
	
    function saveEditor(editor, filePath) {
        var code = encodeURIComponent(editor.getSession().getValue());
		var saveParams = {'filepath': filePath, 'code': code};
		zray.runAction('Online Editor', 'saveCode', saveParams, function(response) {
			if (response.indexOf('error:') == 0) {
				zendDevBar.message.show(response, zendDevBar.MSG_ERROR);
				return;
			}
			zendDevBar.message.show('Saved');
		});
    }

    jQuery('#online-ide-theme').change(function() {
    	var selectedTheme = jQuery(this).val();
    	cookieParams.theme = selectedTheme; 
    	updateCookieParams();
    	jQuery.each(editors, function( index, value ) {
    		value.setTheme(selectedTheme);
  		});
    	jQuery('.online-ide-theme').val(selectedTheme);
    });
    
	zendDevBar.showInIde = function(event, filePath, line, fullUrl, eventsGroupId, writable) {
		zendDevBar.spinner.hide();
		var params = {'filepath': filePath, 'line': line};
		zray.runAction('Online Editor', 'showCode', params, function(response) {
			if (response.indexOf('error:') == 0) {
				zendDevBar.message.show(response, zendDevBar.MSG_ERROR);
				return;
			}
			var writableDiv = writable ? '' : '<div class="online-ide-lock"></div>';
			var rnd = Math.floor(Math.random() * 9999) + 1000;
			var editorWrapper = jQuery('<div id="editor_' + rnd + '_wrapper" class="online-editor">\
					<div class="zdb-col-4"><h1 style="float: left;">' + writableDiv + '<span style="font-size: 14px;color: #006F9D;">' + filePath + '</span></h1><div class="zdb-pull-right"><ul class="zdb-toolbar-items zdb-horizontal"><li class="theme-selector"></li><li><a id="save_editor_' + rnd + '" class="online-ide-save-btn" href="javascript:void(0);" title="Save (ctrl+s)"></a><li><a class="zdb-backtrace-back" href="javascript:void(0);" onclick="jQuery(\'#editor_' + rnd + '_wrapper\').remove();" title="Back (esc)"></a></li></ul></div></div>\
					<div id="editor_' + rnd + '" style="position: absolute; top: 35px; right: 0; bottom: 0; left: 0;"></div></div>');
			jQuery('#online-ide-theme').clone(true).val(jQuery('#online-ide-theme').val()).appendTo(editorWrapper.find('.theme-selector'));
			jQuery(event).closest('.zdb-toolbar-detail').append(editorWrapper);
			jQuery.getScript( "//ajaxorg.github.io/ace-builds/src-min-noconflict/ace.js", function( data, textStatus, jqxhr ) {
				 jQuery('#editor_' + rnd).text(response);
				 var editor = ace.edit("editor_" + rnd);
				 editors.push(editor);
				 if (typeof cookieParams.theme != 'undefined') {
					 editor.setTheme(cookieParams.theme);
				 } else {
					 editor.setTheme("ace/theme/chrome");
				 }
				 editor.getSession().setMode("ace/mode/javascript");

				 if (! writable) {
					   editor.setReadOnly(true);
				 }

				 editor.session.setMode("ace/mode/php");
				 
				 editor.resize(true);
				 editor.scrollToLine(line, true, true, function () {});
				 editor.gotoLine(line);

				 editor.commands.addCommand({
				    name: "save",
				    bindKey: {win: "Ctrl-S", mac: "Command-Option-S"},
				    exec: function(editor) {
				    	saveEditor(editor, filePath);
				    	return true;
				    }
				 });

				 jQuery(document).keyup(function(e) {
					   if (e.keyCode == 27 && editorWrapper != null) {
						   editorWrapper.remove();
						   editorWrapper = null;
					   }
			     });
				 
				 jQuery('#save_editor_' + rnd).click(function() {
					 saveEditor(editor, filePath);
				 });
			});
		});
	}

	var currPath = jQuery('#filepath').val();
	function setPath(path) {
		currPath = path;
		jQuery('#filepath').val(currPath);
		cookieParams.list = currPath; 
    	updateCookieParams();
	}
	function getPath() {
		return currPath;
	}
	function listFiles(path) {
		var params = {'path': path};
    	zray.runAction('Online Editor', 'list', params, function(response) {
    		if (response.indexOf('error:') == 0) {
				zendDevBar.message.show(response, zendDevBar.MSG_ERROR);
				return;
			}
			
    		storage.setData(JSON.parse(response));
    	});
	}
	function humanFileSize(bytes, si) {
	    var thresh = si ? 1000 : 1024;
	    if(Math.abs(bytes) < thresh) {
	        return bytes + ' B';
	    }
	    var units = si
	        ? ['kB','MB','GB','TB','PB','EB','ZB','YB']
	        : ['KiB','MiB','GiB','TiB','PiB','EiB','ZiB','YiB'];
	    var u = -1;
	    do {
	        bytes /= thresh;
	        ++u;
	    } while(Math.abs(bytes) >= thresh && u < units.length - 1);
	    return bytes.toFixed(1)+' '+units[u];
	}
	
    var storage = zray.getStorage('online-editor-list');
    storage.setLimit(-1);

    storage.setSorter('name', function(data, direction) {
        var folders = [];
        var files = [];
        jQuery.each(data, function(key, value) {
            if (value.dir) {
         	   folders.push(value);
            } else {
                files.push(value);
            }
        });

        folders = folders.sort(function(a,b) {
        	if (a.name == '..') {
				if (direction == 'asc') {
				    return -1;
				} else {
					return 1;
				}
			}
        	return a.name.toLowerCase() == b.name.toLowerCase() ? 0 : a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1;
		});
        files = files.sort(function(a,b) {
        	return a.name.toLowerCase() == b.name.toLowerCase() ? 0 : a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1;
		});
		if (direction == 'asc') {
			  return folders.concat(files);
		}
		return files.concat(folders);
        
    	var result = data.sort(function(a,b) {
			return a.dir > b.dir ? -1 : 1;
		});
    	result = result.sort(function(a,b) {
        	if (a.dir == b.dir) {
        		return a.name > b.name ? -1 : 1;
        	}
        	return 0;
			
		});
		return result;
        /*
		var result = data.sort(function(a,b) {
			if (a.name == '..') {
				if (direction == 'asc') {
				    return -1;
				} else {
					return 1;
				}
			}
			
			if (a.dir == b.dir) {
				return a.name.toLowerCase() > b.name.toLowerCase() ? 1 : -1;
			}
			return a.dir > b.dir ? -1 : 1;
		});
		return result;
		*/
	});
	
	// create main table
	var maintable = zray.createTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
	maintable.setColumns([
		{
			label: 'Name',
			propertyName: 'name',
			sortable: true,
			defaultSort: 'asc',
			width: '50%',
			getHtml: function(val, rec) {
				var typeClass = rec.dir ? 'online-ide-folder' : 'online-ide-file';
				var elem = jQuery('<div class="' + typeClass + '">' + val + '</div>');
				
			    elem.click(function() {
				    if (val == '..') {
				    	setPath(rec.path);
				    	listFiles(rec.path);   
				    }
				    else {
    			    	if (rec.dir) {
    			    		setPath(rec.path);
    			    		listFiles(currPath);
    					} else {
    			    		zendDevBar.showInIde(this, rec.path, '1', null, null, rec.writable);
    					}
				    }
			    });
				
        		return elem;
        	}
		},
		{
			label: 'Size',
			propertyName: 'size',
			sortable: true,
			width: '20%',
			getHtml: function(val, rec) {
				if (rec.dir) {
					return '';
				}
			    return humanFileSize(val);
			}
		},
		{
			label: '',
			propertyName: 'writable',
			sortable: false,
			width: '30px',
			getHtml: function(val, rec) {
				if (rec.name == '..') {
					return '';
				}
				if (val) {
					return '';
				}
			    return '<div class="online-ide-lock" title="Read Only"></div>';
			}
		}
	]);
	
	jQuery('#online-editor-form').submit(function (e) {
		e.preventDefault();
		var filePath = jQuery('#filepath').val();
		listFiles(filePath);
	});

	zray.registerExtensionLoaded('Online Editor', function(extensionData, requestData) {
		if (typeof cookieParams.list != 'undefined') {
			setPath(cookieParams.list);
		} else {
			setPath(zray.getExtensionMetadata('Online Editor').metadata.initDir);
		}
		listFiles(currPath);
	});
})();
</script>